import Head from 'next/head'
import { useTranslation } from 'next-i18next'

export default function Home() {
  const { t } = useTranslation()
  return (
    <div>
      <Head>
        <title>{t('header.title')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
